2025-05-12 04:17:06,642 DEBUG    root            Loaded Command Group: ['gcloud', 'compute']
2025-05-12 04:17:07,315 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'scp']
2025-05-12 04:17:07,326 DEBUG    root            Running [gcloud.compute.scp] with arguments: [[[USER@]INSTANCE:]DEST: "techpro-site-vm:/var/www/html/wp-content/themas", [[USER@]INSTANCE:]SRC:1: "['/Users/yamashitakenta/Downloads/wordpressTheme/techpro-j']"]
2025-05-12 04:17:07,326 WARNING  root            The private SSH key file for gcloud does not exist.
2025-05-12 04:17:07,327 WARNING  root            The public SSH key file for gcloud does not exist.
2025-05-12 04:17:07,327 WARNING  root            You do not have an SSH key for gcloud.
2025-05-12 04:17:07,327 WARNING  root            SSH keygen will be executed to generate a key.
2025-05-12 04:17:07,327 DEBUG    root            Running command [/usr/bin/ssh-keygen -t rsa -f /home/yamashitakenta/.ssh/google_compute_engine].
2025-05-12 04:17:07,327 DEBUG    root            Executing command: ['/usr/bin/ssh-keygen', '-t', 'rsa', '-f', '/home/yamashitakenta/.ssh/google_compute_engine']
2025-05-12 04:17:18,682 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/236032490225-compute@developer.gserviceaccount.com/?recursive=true
2025-05-12 04:17:18,712 DEBUG    urllib3.connectionpool Starting new HTTP connection (1): metadata.google.internal:80
2025-05-12 04:17:18,713 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/236032490225-compute@developer.gserviceaccount.com/?recursive=true HTTP/1.1" 200 180
2025-05-12 04:17:18,745 DEBUG    google.auth.transport.requests Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/236032490225-compute@developer.gserviceaccount.com/token
2025-05-12 04:17:18,762 DEBUG    urllib3.connectionpool http://metadata.google.internal:80 "GET /computeMetadata/v1/instance/service-accounts/236032490225-compute@developer.gserviceaccount.com/token HTTP/1.1" 200 869
2025-05-12 04:17:22,128 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): compute.googleapis.com:443
2025-05-12 04:17:22,411 DEBUG    urllib3.connectionpool https://compute.googleapis.com:443 "GET /compute/v1/projects/techpro-official-site/zones/asia-northeast1-a/instances/techpro-site-vm?alt=json HTTP/1.1" 403 None
2025-05-12 04:17:22,415 DEBUG    root            Chosen display Format:list[title="Could not fetch resource:",always-display-title]
2025-05-12 04:17:22,416 DEBUG    root            (gcloud.compute.scp) Could not fetch resource:
 - Request had insufficient authentication scopes.
Traceback (most recent call last):
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 842, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/surface/compute/scp.py", line 188, in Run
    return scp_helper.RunScp(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/compute/scp_utils.py", line 137, in RunScp
    instance = self.GetInstance(compute_client, instance_ref)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/compute/ssh_utils.py", line 533, in GetInstance
    return client.MakeRequests([request])[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/client_adapter.py", line 145, in MakeRequests
    utils.RaiseToolException(
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 139, in RaiseToolException
    RaiseException(problems, calliope_exceptions.ToolException, error_message)
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 148, in RaiseException
    raise exception(
googlecloudsdk.calliope.exceptions.ToolException: Could not fetch resource:
 - Request had insufficient authentication scopes.

2025-05-12 04:17:22,661 ERROR    root            (gcloud.compute.scp) Could not fetch resource:
 - Request had insufficient authentication scopes.

